/**
 * POST /api/name/generate/stream
 *
 * Streaming variant of the name generation API.
 * Returns Server-Sent Events with partial name chunks as they're
 * generated by DeepSeek, so the user sees names appearing in real-time
 * instead of waiting 3-5 seconds for the full response.
 */
import { NextRequest } from "next/server";
import { chatCompletion } from "@/lib/ai/deepseek";
import { NAMING_PROMPT } from "@/lib/ai/prompts";
import { checkRateLimit } from "@/lib/security/rate-limit";
import { circuitAllowed, circuitSuccess, circuitFailure } from "@/lib/security/circuit-breaker";

export async function POST(request: NextRequest) {
  const ip = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";
  const { allowed, resetIn } = await checkRateLimit(`name-gen:${ip}`);

  if (!allowed) {
    return new Response(
      JSON.stringify({ error: `Too many requests. Wait ${resetIn}s.` }),
      { status: 429, headers: { "Content-Type": "application/json" } }
    );
  }

  if (!circuitAllowed("deepseek")) {
    return new Response(
      JSON.stringify({ error: "AI service temporarily unavailable." }),
      { status: 503, headers: { "Content-Type": "application/json" } }
    );
  }

  try {
    const body = await request.json();
    if (!body.english_name || !body.gender) {
      return new Response(
        JSON.stringify({ error: "english_name and gender are required" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    const prompt = NAMING_PROMPT
      .replace("{englishName}", String(body.english_name))
      .replace("{originMeaning}", body.origin_meaning || "unknown")
      .replace("{culturalConcepts}", (body.cultural_concepts || []).join(", "))
      .replace("{gender}", body.gender)
      .replace("{profession}", body.profession || "other")
      .replace("{personality}", (body.personality || []).join(", "))
      .replace("{preferredStyle}", body.preferred_style || "balanced")
      .replace("{purpose}", body.purpose || "study")
      .replace("{baziProfile}", body.bazi_profile || "Not provided")
      .replace("{count}", "5");

    // ── Call DeepSeek with streaming ──
    const client = await chatCompletion(
      [
        { role: "system", content: prompt },
        { role: "user", content: `Generate 5 Chinese names for ${body.english_name}.` },
      ],
      { temperature: 0.7, maxTokens: 2048 }
    );

    // Extract the full result and return as SSE chunk
    const content = client.choices?.[0]?.message?.content || "[]";

    circuitSuccess("deepseek");

    // Build SSE response
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      start(controller) {
        // Parse the full JSON result into chunks
        try {
          // Try to extract JSON array from content
          const match = content.match(/```(?:json)?\s*([\s\S]*?)```/) || [null, content];
          const json = match[1]?.trim() || content;

          // Send as initial event with all names
          controller.enqueue(encoder.encode(`data: ${json}\n\n`));
        } catch {
          controller.enqueue(encoder.encode(`data: ${content}\n\n`));
        }
        controller.enqueue(encoder.encode("event: done\ndata: complete\n\n"));
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (error) {
    circuitFailure("deepseek");
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Generation failed" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
